<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKFoUnqc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKFoUnqc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKFoUnqc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKFoUnqc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKFoUnqc\App_KernelDevDebugContainer([
    'container.build_hash' => 'KFoUnqc',
    'container.build_id' => 'ffa20df6',
    'container.build_time' => 1706451975,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKFoUnqc');
